server/core/urls.py
from django.urls import path, include, re_path
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register(r'api/jobs', views.JobViewSet)

urlpatterns = [
    path('', views.index),
    path('index', views.index, name='index'),
    path('login', views.login_page, name='login'),
    path('queue', views.queue_page, name='queue'),
    path('results', views.results_page, name='results'),
    path('publications', views.publications_page, name='publications'),
    path('contact', views.contact_page, name='contact'),
    path('signup', views.signup_page, name='signup'),
    path('logout', views.logout_page, name='logout'),
    path('details', views.details_page, name='details'),
    path('thankyou', views.thankyou_page, name='thankyou'),
    path('download_file', views.download_file, name='download_file'),
    path('restart_job', views.restart_job, name='restart_job'),
    path('cancel_job', views.cancel_job, name='cancel_job'),
    path('reset_password', views.reset_password_page, name='reset_password'),
    path('settings', views.settings_page, name='settings'),
    re_path('^flower/.*', views.flower, name='flower'),
    path('', include(router.urls)),
    path('api/submit/', views.api_submit),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

server/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files.base import File

import json
import logging
import tempfile
from time import sleep
from path import Path
from celery import shared_task

from . import env
from .utils import upload_file


def _get_task_logger(job_id):
    logger = logging.getLogger(str(job_id))
    logger.setLevel(logging.DEBUG)
    job = Job.objects.get(job_id=job_id)
    h = logging.FileHandler(job.get_dir().joinpath('log.txt'), mode='a')
    f = logging.Formatter('%(asctime)s [%(levelname)s]: %(message)s')
    h.setFormatter(f)
    logger.addHandler(h)
    return logger

# TODO: turn off celery logging. Celery keeps dumping everything to the logfile, which can become really large
@shared_task(bind=True, acks_late=True, track_started=True, default_retry_delay=30, autoretry_for=(Exception,), max_retries=1)
def submit_job(self, job_id):
    logger = _get_task_logger(job_id)
    try:
        job = Job.objects.get(job_id=job_id)
        cur_status = job.status
        if cur_status in Job.STATUS_FINISHED:
            logger.info(f'Starting job {job_id} in L.STR (currently in {cur_status})')
            job.status = 'L.STR'
            job.save()
        else:
            logger.info(f'Starting job {job_id} in {cur_status} (it was interrupted half-way)')

        if job.status == 'L.STR':
            logger.info(f'Started {job.status}')
            sleep(10)
            job.status = 'L.RUN'
            job.save()

        if job.status == 'L.RUN':
            logger.info(f'Running {job.status}')
            sleep(10)

            result = job.term1 + job.term2
            outdir = job.get_output_dir()
            outdir.mkdir_p()
            job.get_result_file().write_text(str(result) + '\n')

            job.status = 'L.FIN'
            job.save()

        if job.status == 'L.FIN':
            logger.info(f'Finalizing {job.status}')
            sleep(10)
            job.status = 'L.CPL'
            job.save()

        if job.status == 'L.CPL':
            logger.info(f'Finished {job.status}')

    except Exception as e:
        logger.exception(e)
        Job.objects.get(job_id=job_id).local_error('Unknown error')
        raise

    return None


class Job(models.Model):
    STATUS_CHOICES = (
        ('L.STR', 'Starting the job'),
        ('L.RUN', 'Running'),
        ('L.FIN', 'Running'),
        ('L.CPL', 'Job completed'),
        ('L.ERR', 'Error'),
    )

    # All other statuses mean the job is still running
    STATUS_FINISHED = ('L.CPL', 'L.ERR')

    job_id = models.AutoField(primary_key=True)
    job_name = models.CharField(max_length=100, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    warning = models.CharField(max_length=1000, blank=True)
    error = models.CharField(max_length=1000, blank=True)
    deleted = models.BooleanField(default=False)
    restarted = models.IntegerField(default=0)
    touched = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ip = models.GenericIPAddressField()
    celery_id = models.CharField(max_length=200, blank=True)

    status = models.CharField(max_length=5, choices=STATUS_CHOICES, default='L.STR')
    details_json = models.CharField(max_length=1000, blank=True)

    _temp_dir = ''

    def __str__(self):
        attr_list = [self.job_id, self.user, self.status]
        return '-'.join(map(str, attr_list))

    def __getattr__(self, attr):
        json_str = super(Job, self).__getattribute__("details_json")
        if json_str:
            json_dict = json.loads(json_str)
            if attr in json_dict:
                return json_dict[attr]
        return super(Job, self).__getattribute__(attr)

    def get_dir(self):
        return env.JOBS_DIR.joinpath(str(self.job_id))

    def get_output_dir(self):
        return self.get_dir().joinpath('output')

    def get_user_dir(self):
        return self.get_dir().joinpath('user')

    def get_user_json(self):
        return self.get_user_dir().joinpath('user.json')

    def get_log_file(self):
        return self.get_dir().joinpath('log.txt')

    def get_result_file(self):
        return self.get_output_dir().joinpath('result.txt')

    def get_result(self):
        with open(self.get_result_file(), 'r') as f:
            r = f.read().strip()
        return r

    def local_error(self, error):
        self.status = 'L.ERR'
        self.error = error
        self.save()

    def reset(self):
        """
        Call this when a job is (re)started. Resets error and warning and increments 'restarted' field
        """
        self.restarted += 1
        self.error = ''
        self.warning = ''
        self.save()

    def start(self):
        if self.celery_id != '':
            result = submit_job.AsyncResult(self.celery_id)
            if not result.ready():
                return [f'Job {self.job_id} is already running (state: {result.state})']
        result = submit_job.apply_async((self.job_id,))
        self.celery_id = result.task_id
        self.restarted += 1
        self.error = ''
        self.warning = ''
        self.save()
        return []

    def cancel(self):
        if self.celery_id != '':
            result = submit_job.AsyncResult(self.celery_id)
            if result.ready():
                return [f'Job has already finished (state: {result.state})']

            result.revoke(terminate=True)
            return [f'Job cancelled (state: {result.state})']
        else:
            return ['Task id is empty']

    def _make_temp_dir(self):
        self._temp_dir = Path(tempfile.mkdtemp(dir=env.TMP_DIR))
        self._temp_dir.chmod(0o755)

    def _create_job_dir(self):
        job_dir = self.get_dir()
        if job_dir.isdir():
            job_dir.rmtree(job_dir)
        self._temp_dir.move(job_dir)

    def check_user_input(self, form, files):
        error_list = []
        self._make_temp_dir()

        user_dir = self._temp_dir.joinpath('user')
        user_dir.mkdir_p()

        # dump user files in user/
        for name, file in files.items():
            fpath = user_dir.joinpath(file.name)
            upload_file(file, fpath)

        # dump user data in user/user.json
        with open(user_dir.joinpath('user.json'), 'w') as f:
            data = {k: (v if not isinstance(v, File) else v.name) for k, v in form.cleaned_data.items()}
            json.dump(data, f, indent=4)

        return error_list

    def make_dir_and_start(self):
        self._create_job_dir()

        clean_json = self.get_user_json()
        with open(clean_json, 'r') as f:
            details_json = json.load(f)
        self.details_json = json.dumps(details_json)
        self.save()

        self.start()

server/core/forms.py
from django import forms
from django.contrib.auth.password_validation import password_validators_help_text_html
from django.core.validators import ValidationError
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.models import User

import re


def validate(input):
    if input <= 0:
        raise ValidationError('Term must be > 0')


class JobSubmitForm(forms.Form):
    job_name = forms.CharField(label='Job name',
                               help_text='Enter your job name here',
                               max_length=100,
                               required=False)

    term1 = forms.IntegerField(label='Term 1 *',
                               help_text='Provide term 1',
                               required=True,
                               validators=[validate])

    term2 = forms.IntegerField(label='Term 2 *',
                               help_text='Provide term 2',
                               required=True,
                               validators=[validate])

    def clean(self):
        cleaned_data = super().clean()
        s1, s2 = cleaned_data.get('term1'), cleaned_data.get('term2')
        if (s1 is not None) and (s2 is not None) and s2 % s1 != 0:
            self.add_error('term2', 'Term 2 must be a multiple of Term 1')

        return cleaned_data


class SettingsForm(forms.Form):
    current_password = forms.CharField(label='Current password',
                                       max_length=100,
                                       required=True,
                                       help_text='Please enter your current password',
                                       widget=forms.PasswordInput(attrs={'class': 'form-control _password'}))

    password = forms.CharField(label='Password',
                               max_length=100,
                               required=True,
                               validators=[validate_password],
                               help_text=password_validators_help_text_html(),
                               widget=forms.PasswordInput(attrs={'class': 'form-control _password'}))


class AcademicEmailField(forms.EmailField):
    def validate(self, value):
        super().validate(value)
        # List based on Wikipedia (https://en.wikipedia.org/wiki/.edu_(second-level_domain) and https://en.wikipedia.org/wiki/.edu_(second-level_domain))
        tld_good = (r'\.edu$', r'\.edu\.[a-z]+$', r'\.ac\.[a-z]+$')
        if not any(re.match(r'^.*@.*'+tld, value) for tld in tld_good):
            raise ValidationError('Your e-mail must belong to an academic domain (.edu, .edu.*, .ac.*)')
        if User.objects.filter(email__exact=value).exists():
            raise ValidationError('Provided email is already in the database')


class SignUpForm(forms.Form):
    email = AcademicEmailField(label='E-mail *',
                               required=True,
                               max_length=1000,
                               help_text='Please, provide a valid academic e-mail address (.edu, .edu.*, .ac.*), we will use it to send you your password',
                               widget=forms.EmailInput(attrs={'class': 'form-control',
                                                              'style': 'width: 40ch'}))

    first_name = forms.CharField(label='First Name',
                                 max_length=1000,
                                 required=False,
                                 widget=forms.TextInput(attrs={'class': 'form-control',
                                                               'style': 'width: 40ch'}))

    last_name = forms.CharField(label='Last Name',
                                max_length=1000,
                                required=False,
                                widget=forms.TextInput(attrs={'class': 'form-control',
                                                              'style': 'width: 40ch'}))


def username_not_exists_validator(value):
    if not User.objects.filter(username__exact=value).exists():
        raise ValidationError('Sorry, we couldn\'t find the e-mail you provided')


class PasswordResetForm(forms.Form):
    username = forms.CharField(label='E-mail',
                               required=True,
                               max_length=1000,
                               help_text='Please, enter your e-mail address',
                               validators=[username_not_exists_validator],
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'style': 'width: 40ch'}))

server/core/templates/core/contact.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}

    <div class="my-fixed-width text-center">
        <h2>Contact</h2>
        Please direct all correspondence to <a href="mailto:youremailaddress">youremailaddress</a>
    </div>
    <br/>

{% endblock %}

server/core/templates/core/details.html
{% extends "core/base.html" %}

{% block content %}
    <div class="row my-fixed-width">
        <div class="text-center">
            <h2>Job {{ job.job_id }}</h2>
            <br>
            <table class="table table-hover table-bordered table-responsive my-fixed-width">
                <thead>
                <tr>
                    <th style="text-align: center;">Id</th>
                    <th style="text-align: center;">Name</th>
                    <th style="text-align: center;">User</th>
                    <th style="text-align: center;">Status</th>
                </tr>
                </thead>

                <tbody>
                <tr>
                    <td>{{ job.job_id }}</td>
                    <td>{{ job.job_name|slice:":20"|default:job.job_id }}{% if job.job_name|length > 20 %}..{% endif %}</td>
                    <td>{{ job.user.username|slice:":20" }}{% if job.job_name|length > 20 %}..{% endif %}</td>
                    <td>{% if job.error %}{{ job.error }}{% else %}{{ job.get_status_display }}{% endif %}</td>
                </tr>
                </tbody>
            </table>
        </div>

        <hr>
        <div style="display: table; margin: auto">
            <h4 align="center">Details</h4>
            <br>
            {% if job.details_json %}
                <p>Term 1: {{ job.term1 }}</p>
                <p>Term 2: {{ job.term2 }}</p>
            {% endif %}
        </div>

        {% if job.status in job.STATUS_FINISHED %}
            <hr>
            <h4 align="center">Downloads</h4>
            <br>

            {% if job.status == 'L.CPL' %}
                <p align="center">Result: {{ job.get_result }}</p>
                <br>
            {% endif %}

            <div style="display: table; margin: auto">
                <a style="width: 100%" type="button" class="btn btn-default"
                   href="{% url 'download_file' %}?job_id={{ job.job_id }}&content=log.txt">
                    <span class="glyphicon glyphicon-download-alt"></span>
                    Download log
                </a>
            </div>
        {% endif %}
        <br/><br/><br/>
    </div>
{% endblock %}

server/core/templates/core/generic_form.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <h3 align="center">{{ page_title }}</h3>
    <p align="center">{{ page_description }}</p>
    <form class="my-generic-form" action={% url request.resolver_match.url_name %} method="post">
        {% csrf_token %}
        <div class="_generic_form">
            {% for field in form %}

                <div class="form-group {% if field.errors %}has-error has-feedback{% endif %}">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                    {% endif %}
                </div>

                {% if field.help_text %}
                    <p class="_help-text" align="center">{{ field.help_text }}</p>
                {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary btn-md" style="margin-top: 25px" value="submit">{{ submit_text }}</button>
        </div>
    </form>
{% endblock %}

server/core/templates/core/home.html
{% extends "core/base.html" %}
{% load static %}

{% block header_add %}
    <link rel='stylesheet' type='text/css' href={% static "core/css/home.css" %} xmlns="http://www.w3.org/1999/html"/>
    <link rel='stylesheet' type='text/css' href={% static "core/css/spinner.css" %} />
    <link rel='stylesheet' type='text/css' href={% static "core/css/apple-checkbox.css" %} />
{% endblock %}

{% block content %}
    <form class="form-jobs" enctype='multipart/form-data' action={% url "index" %} method='post'>
    {% csrf_token %}
        <h1 align="center">Job submission</h1>
        <hr>
        <h4 align="center">Add two numbers together</h4>
        <br>

        {# Job name #}
        <div class="row">
            <div class="col-sm-4 col-sm-offset-4">
                <div class="form-group {% if form.job_name.errors %}has-error has-feedback{% endif %}"
                     style="text-align: center;">
                    <label for="id_job_name" style="font-weight: normal;">{{ form.job_name.label }}</label>
                    <input class="form-control center-text"
                           style="height: 40px; margin:auto;"
                           type="text" name="job_name" id="id_job_name" placeholder="Job name" maxlength="100"/>
                    {% if form.job_name.errors %}
                        <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                    {% endif %}
                    <p class="_help-text" align="center">{{ form.job_name.help_text }}</p>
                </div>
            </div>
        </div>

        <br>

        {# Parameters #}
        <div class="row">
            <div class="col-sm-4 col-sm-offset-2">
                <div style="display: flex; justify-content: center; align-items: center">
                    <div class="form-group {% if form.term1.errors %}has-error has-feedback{% endif %}"
                         style="text-align: center;">
                            <label for="id_term1" style="font-weight: normal;">{{ form.term1.label }}</label>
                            <input type="text"
                                   class="form-control center-text"
                                   style="margin:auto; height:40px;"
                                   name="term1" id="id_term1" placeholder=2 maxlength="10000" required>
                            {% if form.term1.errors %}
                                <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                            {% endif %}
                        <p class="_help-text" align="center">{{ form.term1.help_text }}</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div style="display: flex; justify-content: center; align-items: center">
                    <div class="form-group {% if form.term2.errors %}has-error has-feedback{% endif %}"
                         style="text-align: center;">
                            <label for="id_term2" style="font-weight: normal;">{{ form.term2.label }}</label>
                            <input type="text"
                                   class="form-control center-text"
                                   style="margin:auto; height:40px;"
                                   name="term2" id="id_term2" placeholder=6 maxlength="10000" required>
                            {% if form.term2.errors %}
                                <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                            {% endif %}
                        <p class="_help-text" align="center">{{ form.term2.help_text }}</p>
                    </div>
                </div>
            </div>
        </div>

        <br>
        <hr>

        {% if user.username == "anonym" %}
            <div style="display: flex; justify-content: center">
                <div class="form-group" style="margin: 0 auto; width: fit-content; width: -moz-fit-content">
                    <input type="checkbox" id="id_noncommercial" class="ios8-switch ios8-switch-lg" required>
                    <label for='id_noncommercial' style="font-weight: normal; line-height: 20px;">
                        I will use {{ SERVER_NAME }} for non-commercial purposes only
                    </label>
                </div>
            </div>
        {% endif %}

        {# Submit button #}
        <div class="form-group jobs-submit text-center">
            <button type="submit" class="btn btn-primary btn-md" id="submit_button" name="action" value="submit">Submit job</button>
        </div>

        <div id="spinner" style="display: none">
            <p align="center">Processing input..</p>
            <div class="spinner" style="margin: auto;"></div>
        </div>
    </form>

{% endblock %}

server/core/templates/core/jobs.html
{% extends "core/base.html" %}
{% load static %}

{% block header_add %}
    <link rel='stylesheet' type='text/css' href={% static "core/css/progress-bar.css" %} />
{% endblock %}

{% block content %}
    <h2 align="center">
        {% if request.resolver_match.url_name == "results" %}
            Results
        {% elif request.resolver_match.url_name == "queue" %}
            Queue
        {% endif %}
    </h2>
    <br>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">  {# TODO: Fix the layout for small screens, in admin mode it doesn't fit #}
            <table class="table table-hover table-bordered table-responsive" style="text-align: center; margin: auto">
                <thead>
                    <tr>
                        <th style="text-align: center; padding: 0; justify-content: center;
                                {% if order_by == '-job_id' %}
                                    border-bottom-width: 3px; border-bottom-color: #51ad4c;
                                {% endif %}">
                            <a style="display: block; padding: 5px; color: black" href="{{ request.path }}?order_by=-job_id">Id</a>
                        </th>
                        <th style="text-align: center; padding: 0; justify-content: center;
                                {% if order_by == 'job_name' %}
                                    border-bottom-width: 3px; border-bottom-color: #51ad4c;
                                {% endif %}">
                            <a style="display: block; padding: 5px; color: black"href="{{ request.path }}?order_by=job_name">Name</a>
                        </th>
                        <th style="text-align: center; padding: 0; justify-content: center;
                                {% if order_by == 'user__username' %}
                                    border-bottom-width: 3px; border-bottom-color: #51ad4c;
                                {% endif %}">
                            <a style="display: block; padding: 5px; color: black" href="{{ request.path }}?order_by=user__username">User</a>
                        </th>
                        <th style="text-align: center; padding: 0; justify-content: center;
                                {% if order_by == 'status' %}
                                    border-bottom-width: 3px; border-bottom-color: #51ad4c;
                                {% endif %}">
                            <a style="display: block; padding: 5px; color: black" href="{{ request.path }}?order_by=status">Status</a>
                        </th>
                        {% if user.is_superuser %}
                            <th style="text-align: center; padding: 0;">
                                <div style="padding: 5px">Restart</div>
                            </th>
                        {% endif %}
                    </tr>
                </thead>

                <tbody>
                    {% for job in jobs %}
                        <tr>
                            <td><a href="{% url 'details' %}?job_id={{ job.job_id }}">{{ job.job_id }}</a></td>
                            <td>{{ job.job_name|slice:":20"|default:job.job_id }}{% if job.job_name|length > 20 %}..{% endif %}</td>
                            <td>{{ job.user.username|slice:":20" }}{% if job.user.username|length > 20 %}..{% endif %}</td>
                            <td>
                                {{ job.get_status_display }}{{ job.get_queue_status_display }}
                                <div class="job-progress
                                {% if job.status == "L.ERR" %}
                                    job-progress-error
                                {% elif job.status == "L.STR"%}
                                    job-progress-start
                                {% elif job.status == "L.RUN"%}
                                    job-progress-running
                                {% elif job.status in job.STATUS_FINISHED %}
                                    job-progress-complete
                                {% endif %}"></div>
                            </td>
                            {% if user.is_superuser %}
                                <td><a href="{% url 'restart_job' %}?job_id={{ job.job_id }}">Restart</a></td>
                                <td><a href="{% url 'cancel_job' %}?job_id={{ job.job_id }}">Cancel</a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                <tbody>
            </table>
        </div>
    </div>

    <div class="my-fixed-width my-padded text-center">
        <ul class="pagination pagination-sm">
            <li {% if not jobs.has_previous %}class="disabled"{% endif %}>
                <a href="?page=1">First</a>
            </li>
            <li {% if not jobs.has_previous %}class="disabled"{% endif %}>
                <a href="?page={% if jobs.has_previous %}{{ jobs.previous_page_number }}{% else %}#{% endif %}">Previous</a>
            </li>

            <li class="active"><a href="#">{{ jobs.number }}</a></li>

            <li {% if not jobs.has_next %}class="disabled"{% endif %}>
                <a href="?page={% if jobs.has_next %}{{ jobs.next_page_number }}{% else %}#{% endif %}">Next</a>
            </li>
            <li {% if not jobs.has_next %}class="disabled"{% endif %}>
                <a href="?page={{ jobs.paginator.num_pages }}">Last &raquo;</a>
            </li>
        </ul>
    </div>
{% endblock %}

server/core/templates/core/login.html
{% extends "core/base.html" %}

{% block content %}

<div class="jumbotron">
	<h1>Welcome to {{ SERVER_NAME }}</h1>
	<p>Template web-server you can do whatever you want with</p>
    <a class="btn btn-md btn-default" href="{% url 'login' %}?anonym=true" style="max-width: 100%">
        Use the server without the benefits of your own account &raquo;
    </a>
</div>

<form class="form-horizontal my-signin-form" enctype="multipart/form-data" action={% url "login" %} method="post">
    {% csrf_token %}

	<h2 class="white-outline">Please sign in</h2>

    <div class="form-group">
        <input type="text" id="username" class="form-control" name="username"
               value="" placeholder="E-mail" required autofocus>
    </div>

    <div class="form-group">
        <input type="password" id="password" class="form-control" name="password"
               value="" placeholder="Password" required>
    </div>

    <div class="form-group">
        <a class="btn btn-sm btn-link white-outline" style="color: black;" href='{% url "reset_password" %}'>Forgot password?</a>
    </div>

     <div class="text-center">
	    <button class="btn btn-md btn-success btn-block" type="submit" name="action" value="Login">Sign in</button>
     </div>
</form>

{% endblock %}

server/core/templates/core/publications.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <div class="my-fixed-width text-center">
        <h2>Papers</h2>
        <ol class="text-left">
                <li>Authors
                  <i>"Title&rdquo;</i>
                  submitted to Journal (2019)
              </li>
        </ol>
    </div>
{% endblock %}

server/core/templates/core/thankyou.html
{% extends "core/base.html" %}

{% block content %}

<div class="jumbotron">
	<h1>Thank you for signing up</h1>
	<p>Your password will arrive in the e-mail you provided shortly</p>
    <br><br>
    <a class="btn btn-md btn-default" href="{% url 'login' %}?anonym=true" style="max-width: 100%">
        You can log in now using your credentials
    </a>
</div>

{% endblock %}